name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: app
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: app
        run: python -m pytest

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login nourcloudregistry.azurecr.io \
          --username "${{ secrets.ACR_USERNAME }}" \
          --password-stdin

      - name: Build Docker image
        working-directory: app
        run: |
          docker build \
          -t nourcloudregistry.azurecr.io/cloud-infra-app:${{ github.sha }} \
          -t nourcloudregistry.azurecr.io/cloud-infra-app:latest \
          .

      - name: Push Docker image
        run: |
          docker push nourcloudregistry.azurecr.io/cloud-infra-app:${{ github.sha }}
          docker push nourcloudregistry.azurecr.io/cloud-infra-app:latest
            - name: Set Kubernetes context
        uses: azure/k8s-set-context@v5
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/cloud-infra-app \
            cloud-infra-app=nourcloudregistry.azurecr.io/cloud-infra-app:${{ github.sha }}

          kubectl rollout status deployment/cloud-infra-app
